version: "3.7"

x-network: &network
    networks:
        - default

services:
    apache:
        build: ./docker/apache
        container_name: ${PROJECT_NAME}_apache
        # depends_on:
        #     - mysql
        volumes:
            - ./docker/apache/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./server:/var/www/symfony:cached
        expose:
            - 80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${DOMAIN_NAME}`)"
            - "traefik.http.routers.${PROJECT_NAME}_apache.tls.certresolver=leresolver"
            - "traefik.http.routers.${PROJECT_NAME}_apache.entrypoints=websecure"
        <<: *network

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_pma
        depends_on:
            - mysql
        expose:
            - 80
        environment:
            PMA_HOST: mysql
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${DOMAIN_NAME}`)"
            - "traefik.http.routers.${PROJECT_NAME}_pma.tls.certresolver=leresolver"
            - "traefik.http.routers.${PROJECT_NAME}_pma.entrypoints=websecure"
        <<: *network

    # MySQL
    mysql:
        image: mysql:8
        container_name: ${PROJECT_NAME}_mysql
        volumes:
            - ./docker/mysql/db-data:/var/lib/mysql
            - ./docker/data:/data
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        <<: *network

networks:
  default:
    external:
        name: ${PROJECT_NETWORK}
