version: "3.7"

services:

    apache:
        image: kabaconde/symfony-apache
        container_name: ${PROJECT_NAME}-apache
        depends_on:
            - mysql
        volumes:
            - ./docker/apache/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./server:/var/www/symfony:cached
        ports:
            - 80:80
    # MySQL
    postgres:
        image: postgres:12-alpine
        container_name: ${PROJECT_NAME}-postgres
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
