version: "3.7"

services:

    apache:
        image: kabaconde/symfony-apache
        container_name: ${PROJECT_NAME}-apache
        depends_on:
            - mysql
        volumes:
            - ./docker/apache/apache2.conf:/etc/apache2/conf-enabled/apache2.conf:ro
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./app:/var/www/symfony:cached
        ports:
            - 80:80
    # MySQL
    mysql:
        image: mysql:8
        container_name: ${PROJECT_NAME}-mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
