api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']

    collection:
        pagination:
            enabled: true
            client_enabled: true
            enabled_parameter_name: pagination # optional
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage # Default value

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
