security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # order is important here (api must be placed before api_login)
        api:
            pattern: ^/api/
            stateless: true
            anonymous: true
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            stateless: false
            anonymous: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_PHARMACY: [ROLE_USER]
        ROLE_INTERN: [ROLE_USER]

    access_control:
    - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/forgot-password-request, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/regions, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
    - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
