<?php

namespace App\Command;

use App\Command\AddJobCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class InsertAllJobCommand extends Command
{
    protected static $defaultName = 'app:job:insert-all';

    protected function configure()
    {
        $this
            ->setDescription('Insert all initial job data');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $commandName = AddJobCommand::getDefaultName();
        $command = $this->getApplication()->find($commandName);

        foreach ($this->getJobs() as $job) {
            $arguments = [
                'command' => $commandName,
                'jobTitle'    => $job,
            ];

            $jobInput = new ArrayInput($arguments);
            $returnCode = $command->run($jobInput, $output);
            if ($returnCode != 0) {
                $io->note("Command fails with $job value");
                break;
            }
        }

        $io->success(sprintf('All job have been saved'));

        return 0;
    }

    private function getJobs()
    {
        return [
            'AccËs au remboursement',
            'Achat de produits de santÈ pharmaceutique',
            'Achats',
            'Achats mÈdicaments',
            'Adapt patho',
            'Aff Med Glob',
            'Aff Med/Clinical Project Manager',
            'Aff Reg',
            'Affaires cliniques',
            'Affaires Medicales',
            'Affaires mÈdicales',
            'Affaires mÈdicales FertilitÈ Endocrinologie',
            'Affaires mÈdicales globales Grippe',
            'Affaires mÈdicales oncologiques',
            'Affaires Medicales- Gestion de projets',
            'Affaires Pharmaceutiques',
            'Affaires publiques globales Vaccins',
            'Affaires Reglementaires',
            'Affaires rÈglementaires',
            'Affaires rËglementaires',
            'Ana Pat',
            'Analyse Gestion',
            'Anapath',
            'Anapath, biologie des tumeurs',
            'Antibio-prÈparation stÈrile',
            'AP',
            'AP/cont',
            'Appro',
            'Appro et distribution - Materiovig - GDR',
            'Appro, DÈlivrance et vigilance des mÈdicaments',
            'Appro/dÈlivrance des produits de santÈ',
            'AQ',
            'AQ Affaires rÈglementaires',
            'AQ Compliance',
            'AQ OpÈrationnelle dengue',
            'AQ OpÈrationnelle prod',
            'AQ/CQ',
            'AR',
            'AR/AQ',
            'Bacterio',
            'BactÈrio',
            'Bacterio N2',
            'Bacteriologie',
            'BDR',
            'Bio Cel',
            'Bioch',
            'Bioch N1',
            'Bioch/Bio mol',
            'Biochimie',
            'Biochimie/Bio mol',
            'Biologie',
            'Biostat',
            'Biotech cell',
            'CAQES',
            'CBU DMI - NPI',
            'CBU MÈdicament',
            'Chimios',
            'CIC',
            'CIRE',
            'Clin/Infect',
            'Clinical Pharmacology Modeling&Simulation',
            'ContrÙles',
            'CQ',
            'CRPV',
            'CRTH',
            'CTF',
            'Cyclotron neuro-pharmaco',
            'Cyto',
            'Cyto + Conciliation',
            'Cyto + Dispensation contrÙlÈe',
            'Cyto + Essais cliniques',
            'Cyto/Radiophar',
            'Cytogenet',
            'Cytogenetique',
            'DAI-Parasito',
            'DAI-Viro',
            'DBPC',
            'DBPT',
            'DBTP',
            'Dem',
            'DÈpartement scientifique',
            'DÈrogation RI',
            'DiabÈtologie',
            'Direction mÈdicale',
            'Disp',
            'Disp (GM)',
            'Disp Dermato',
            'Disp Med Digestive',
            'Disp Pedia',
            'Dispensation HÈmato',
            'Dispensation journaliËre nominative / PC',
            'Dispo',
            'DM',
            'DM StÈ',
            'DM/MTV',
            'DMI',
            'DMS',
            'DMS/Ste',
            'DOC - ATU',
            'Dotations aux unitÈs de soins',
            'DRCI',
            'DYCOG',
            'EA 4129P2S Parcours SantÈ SystÈmique',
            'EA 4676',
            'EA 4676 PC/Biotech',
            'EA4169 Equipe formules pharmaceutiques',
            'EC',
            'EC Divers thÈrapeutiques',
            'EC/ATU',
            'EC/chimio',
            'Eco',
            'Eco',
            'Eco Vig',
            'Eco/Vig',
            'Economie individuelle et sociÈtale',
            'EH',
            'EH BiogalÈnique',
            'EH CRC Inserm',
            'EH Cyclotron',
            'EH Inserm U851',
            'EH Physio-Pharmaco',
            'EMR 3738',
            'Endocrinologie molÈculaire',
            'Enregistrement',
            'Equipe THEREX du laboratoire TIMC-UGA',
            'Essais cliniques -ATU',
            'Essais Cliniques ATU',
            'EUROPE',
            'Europe Market Access',
            'Evaluation mÈdicale',
            'Extra-hospitalier',
            'Extra-hospitalier Institut Albert Bonniot',
            'Extra-hospitalier unitÈ HESPER',
            'FDC',
            'GalÈnique',
            'Genet',
            'Genetique',
            'GÈnÈtique',
            'GÈriatrie',
            'Gestion',
            'Glob. Med. Strat. Pneum. Mening & new tech',
            'Global ÈpidÈmiologique',
            'Global Market Immunoassays',
            'Global Medical - Innovative Medical Engagement',
            'Global Medical - Medical Operation',
            'Global Medical - Travel Endemic & Dengue Franchise',
            'Global Medical Affairs',
            'Global Medical Affairs - Field Based Medical',
            'Global Medical Affairs Compliance',
            'Global pharmacovigilance department',
            'HDJ HÈmato Onco',
            'HDJ Thorax',
            'Health Economics and Value Assessment',
            'Hem/Biomol',
            'Hemato',
            'HÈmato',
            'Hemato N1',
            'Hematologie',
            'HÈmatologie spÈcialisÈe',
            'Henri Gab - Chir',
            'HÈpato gastro',
            'HESPER',
            'Heva Pole Consultants',
            'Hormonologie',
            'Hospital marketing and sales director',
            'Hygiene',
            'HygiËne',
            'Hygiene - EH',
            'HygiËne / SantÈ publique',
            'IHOP',
            'Immuno',
            'Immuno hÈmato',
            'Immuno/hÈmato',
            'Immunologie',
            'Infectio Clin',
            'Infectiologie',
            'InfoMed + Validation',
            'Information MÈdicale',
            'InterChu',
            'Labo Pharm clin et biotech',
            'Labo pharmacie galÈnique',
            'Labo Sub Cut',
            'LCQ',
            'Lysarc',
            'M&S Pharmacology AQS',
            'Mal Her Metabolisme',
            'Mal Inf et Trop',
            'maladies mÈtaboliques hÈrÈditaires',
            'MarchÈ et evaluation mÈdico Èconomique',
            'Market Access',
            'matÈriovigilance',
            'MED',
            'Med/ATB',
            'Med/Doc',
            'MÈdecine reproduction',
            'Medicaments',
            'MÈdico-Èconomie',
            'Microbio',
            'Microbiologie',
            'MPR',
            'NÈphrologie',
            'Neuro Onco',
            'Neurobio',
            'Neurologie',
            'Novartis Pharma SAS (Rueil)',
            'Nutrition',
            'OMEDIT',
            'Oncologie',
            'Parasito',
            'Parasito N2',
            'Parasito/Myco',
            'Parasitologie',
            'Pas de choix',
            'PC',
            'PC / MÈdicament',
            'PC / Polyvalent',
            'PC Disp',
            'PC GÈriatrie',
            'PC onco',
            'PÈdiatrie',
            'Pharmacie',
            'Pharmacie clinique adulte / Dispensation nominativ',
            'Pharmacie clinique pÈdiatrique / Dispensation nomi',
            'Pharmaco',
            'Pharmaco-Tox',
            'Pharmaco/Tox',
            'Pharmacologie',
            'Pharmacotech',
            'Pharmacotechnie',
            'Pharmacotechnie / Laboratoire de ContrÙle',
            'Pharmacovigilance',
            'PK Clin',
            'Pneumologie',
            'POL',
            'Pol - PC-Disp',
            'Polyvalent',
            'PUI',
            'PÙle excellence mÈdicale',
            'PÙle IMER',
            'PÙle IMRA',
            'PÙle innovation cardio',
            'PV',
            'PV Affaires rÈglementaires',
            'PV/AQ',
            'PV/Reg',
            'PV+AQ',
            'R&D',
            'Radio Pharmacie',
            'Radiophar',
            'Radiophar Neuro-pharmacologie',
            'Radiopharm',
            'Recherche et dÈveloppement',
            'Relations hospitaliËres oncologiques',
            'Ressource humaine',
            'RÈtrocession-HAD-ATU',
            'Rhumatologie',
            'RP',
            'Services mÈdicaux',
            'Servier',
            'SNV',
            'SSPAS',
            'SSR Cardio',
            'StÈrilisation',
            'StratÈgie dÈveloppement onco',
            'SystËme de qualitÈ des laboratoires',
            'T2A / CAQES',
            'TIMC-IMAG (EH)',
            'Toxicologie',
            'ToxicoVig',
            'U1039',
            'U623',
            'UMR 5525 THEMAS',
            'UMR 5557',
            'UMR 5558',
            'UMR CNRS 5525 TIM-IMAG',
            'UMR CNRS 5525 TIMC-IMAG',
            'UMR CNRS 5558',
            'UMR CNRS LAGEP',
            'UMR INSERM',
            'UPAC (ex URCC)',
            'UPCO',
            'URCC',
            'Vaccination Policy Advocacy',
            'Val/Fametero',
            'Valorisation stratÈgique Affaires MÈdicales',
            'Vigilance des EC',
            'Viro',
            'Viro N2',
            'Virologie',
        ];
    }
}
